# Generated by Django 3.1.5 on 2021-02-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseDetect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdetect',
            name='detected_disease',
            field=models.TextField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
