# Generated by Django 3.1.5 on 2021-02-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseDetect', '0002_plantdetect_detected_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_disease', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantdetect',
            name='detected_disease',
        ),
    ]
