# Generated by Django 3.1.5 on 2021-02-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseDetect', '0004_auto_20210212_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasedetect',
            old_name='ImageName',
            new_name='ImagePath',
        ),
    ]
