# Generated by Django 3.1.5 on 2021-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseDetect', '0005_auto_20210212_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedetect',
            name='ImagePath',
            field=models.URLField(max_length=300),
        ),
    ]
