# Generated by Django 3.1.6 on 2021-02-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseDetect', '0006_auto_20210212_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiseaseDetect',
        ),
        migrations.AddField(
            model_name='plantdetect',
            name='ImagePath',
            field=models.URLField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
