# Generated by Django 3.1.6 on 2021-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseDetect', '0007_auto_20210226_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdetect',
            name='ImagePath',
        ),
        migrations.AddField(
            model_name='plantdetect',
            name='disease_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
